paths:
  - ./src
  - ./tests

layers:
  - name: Bundle
    collectors:
      - type: className
        regex: \\Janwebdev\\SocialPostBundle\\.*
  - name: Tests
    collectors:
      - type: className
        regex: \\Tests\\Janwebdev\\SocialPostBundle\\.*

ruleset:
  Bundle: ~
  Tests:
    - Bundle
